server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esta línea sustituye la lógica de tu archivo _redirects:
        try_files $uri $uri/ /index.html;
    }

    # Para que no te salgan errores de favicon en los logs
    location = /favicon.ico { 
        log_not_found off; 
        access_log off; 
    }
}