ALTER TABLE manual_cuts ADD COLUMN IF NOT EXISTS cash_count JSONB DEFAULT NULL;
ALTER TABLE manual_cuts ADD COLUMN IF NOT EXISTS cash_counted_total NUMERIC(14,2) DEFAULT NULL;
ALTER TABLE manual_cuts ADD COLUMN IF NOT EXISTS cash_difference NUMERIC(14,2) DEFAULT NULL;
